<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'api_platform.jsonld.action.context' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/JsonLd/Action/ContextAction.php';

return $this->services['api_platform.jsonld.action.context'] = new \ApiPlatform\Core\JsonLd\Action\ContextAction(${($_ = isset($this->services['api_platform.jsonld.context_builder']) ? $this->services['api_platform.jsonld.context_builder'] : $this->getApiPlatform_Jsonld_ContextBuilderService()) && false ?: '_'}, ${($_ = isset($this->services['ApiPlatform\Core\Metadata\Resource\Factory\ResourceNameCollectionFactoryInterface']) ? $this->services['ApiPlatform\Core\Metadata\Resource\Factory\ResourceNameCollectionFactoryInterface'] : $this->getResourceNameCollectionFactoryInterfaceService()) && false ?: '_'}, ${($_ = isset($this->services['ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface']) ? $this->services['ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface'] : $this->getResourceMetadataFactoryInterfaceService()) && false ?: '_'});
