<?php

namespace AppBundle\Repository;

/**
 * PassionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassionsRepository extends \Doctrine\ORM\EntityRepository
{
}
