<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYl5pvhr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYl5pvhr/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYl5pvhr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYl5pvhr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYl5pvhr\appProdProjectContainer(array(
    'container.build_hash' => 'Yl5pvhr',
    'container.build_id' => '8e040992',
    'container.build_time' => 1518446927,
));
