<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.operation_path_resolver.default' shared service.

@trigger_error('The "api_platform.operation_path_resolver.default" service is deprecated since API Platform 2.1 and will be removed in 3.0. Use "api_platform.path_segment_name_generator.underscore" instead.', E_USER_DEPRECATED);

return $this->services['api_platform.operation_path_resolver.default'] = new \ApiPlatform\Core\PathResolver\UnderscoreOperationPathResolver();
