<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.listener.view.validate' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Bridge/Symfony/Validator/EventListener/ValidateListener.php';

return $this->services['api_platform.listener.view.validate'] = new \ApiPlatform\Core\Bridge\Symfony\Validator\EventListener\ValidateListener(${($_ = isset($this->services['validator']) ? $this->services['validator'] : $this->getValidatorService()) && false ?: '_'}, ${($_ = isset($this->services['ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface']) ? $this->services['ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface'] : $this->getResourceMetadataFactoryInterfaceService()) && false ?: '_'}, $this);
