<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'api_platform.action.documentation' shared service.

include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Documentation/Action/DocumentationAction.php';

return $this->services['api_platform.action.documentation'] = new \ApiPlatform\Core\Documentation\Action\DocumentationAction(${($_ = isset($this->services['ApiPlatform\Core\Metadata\Resource\Factory\ResourceNameCollectionFactoryInterface']) ? $this->services['ApiPlatform\Core\Metadata\Resource\Factory\ResourceNameCollectionFactoryInterface'] : $this->getResourceNameCollectionFactoryInterfaceService()) && false ?: '_'}, '', '', '0.0.0', $this->parameters['api_platform.formats']);
