<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.swagger.command.swagger_command' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Command/SwaggerCommand.php';

return $this->services['api_platform.swagger.command.swagger_command'] = new \ApiPlatform\Core\Bridge\Symfony\Bundle\Command\SwaggerCommand(${($_ = isset($this->services['api_platform.swagger.normalizer.documentation']) ? $this->services['api_platform.swagger.normalizer.documentation'] : $this->getApiPlatform_Swagger_Normalizer_DocumentationService()) && false ?: '_'}, ${($_ = isset($this->services['ApiPlatform\Core\Metadata\Resource\Factory\ResourceNameCollectionFactoryInterface']) ? $this->services['ApiPlatform\Core\Metadata\Resource\Factory\ResourceNameCollectionFactoryInterface'] : $this->getResourceNameCollectionFactoryInterfaceService()) && false ?: '_'}, '', '', '0.0.0', $this->parameters['api_platform.formats']);
