<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTn37u2s\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTn37u2s/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTn37u2s.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTn37u2s\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTn37u2s\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Tn37u2s',
    'container.build_id' => '5c1398b2',
    'container.build_time' => 1522076547,
));
